### ISSUE TITLE
Adapt runApp()

### ISSUE THREAD

**Issue by mvarewyck** [openefsa/mssTablesToExcel#1]
@behrica I tried to deploy the app on shinyProxy

* The function `mssTablesToExcel::runApp()` is not exported. In NAMESPACE there is a function `runShiny` instead.
* I would recommend not to overwrite `shiny::runApp()`, therefore it is best to use another name e.g. `runShiny`
* We use a template for the runApp function (see below). The argument `installDependencies` allows that users can run the app locally (offline) without further installations.

```
#' Run the shiny application
#' @param installDependencies boolean, whether to first install packages listed
#' in the Suggests field of DESCRIPTION; default value is FALSE
#' @param ... further arguments that can be passed to \code{\link[shiny]{runApp}}
#' @return no return value
#' @importFrom shiny runApp
#' @importFrom stats update
#' @importFrom devtools dev_package_deps
#' @export
runTmp <- function(installDependencies = FALSE, ...) {
  
  # (1) Install all suggested R packages (see DESCRIPTION)
  if (installDependencies) {
    
    ## (a) CRAN packages
    update(dev_package_deps(pkg = system.file("ui", package = "tmp"), 
            dependencies = "Suggests"))
    
    
#    ## (b) non-CRAN packages - by hand
#    if (!requireNamespace("shiny.collections")) {
#      
#      install_github("Appsilon/shiny.collections")
#      
#    }
    
  }
  
  # (2) Run the application
  ldots <- list(...)
  
  if (!is.null(ldots$appDir))
    runApp(...) else
    runApp(appDir = system.file("ui", package = "toxicityPrediction"), ...)
  
}
```

**Comment by behrica** [comment]
I just pushed a new release, r0.0.2 with the changes you proposed.
@mvarewyck , please check it and let me know

**Comment by mvarewyck** [comment]
OK. I had to update NAMESPACE and added tidyverse in suggests field of DESCRIPTION (I am not able to push my changes)

**Comment by behrica** [comment]
I just gave you permission

**Comment by behrica** [comment]
Hi @mvarewyck ,
any progress on this from your side ?
Is there anything left to do fro me, before you can deploy the app in EFSA's server ?

**Comment by mvarewyck** [comment]
Hi @behrica 

Sorry, I informed Jose Cortinas Abrahantes that the app is online (I did not have your EFSA e-mail address), available at https://shiny-efsa.openanalytics.eu/app/mss-to-excel
If you don't have access, Jose can give you.
If you would experience any problems with the deployed app, feel free to create new issue.

Cheers,
Machteld

**Comment by behrica** [comment]
Hi Mechteld,
the application work now, thanks.

I suppose you deploy it via Docker, right ?

So fort the next time, I can provide you as well with a Dockerfile,
this should make your work for deploying it easier.

Do you have a specific base image you use ? 
Is it always "openanalytics/r-base" as written in the shiny-proxy documentation at 
https://www.shinyproxy.io/deploying-apps/ ?

If I use the same for local testing here, it should guarant that it works on your side as well.

My email at EFSA is carsten.behring@efsa.europa.eu

**Comment by mvarewyck** [comment]
(1) Correct, deployment is via Docker. 

(2, 4) Adapting the dockerfile is not much work (adding 4 lines of code). The docker image we build includes multiple applications for EFSA, so if you provide a Dockerfile I will copy/paste these lines to our Dockerfile, e.g. [Dockerfile.txt](https://github.com/openefsa/mssTablesToExcel/files/1618377/Dockerfile.txt). However, it is indeed good practice to test new applications first with Docker locally. This will guarantee that it works on any machine using the same statements in the Dockerfile.
For future new applications, we basically need:
* the .tar.gz file with the package
* specification of R-packages needed within the application and that were not loaded via Import field in DESCRIPTION file. Ideally these R-packages are in the Suggests field.
* Name of the app to be displayed on the website

(3) Correct, we use r-base image.
